name: build

on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-java-library:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Java/Concentus
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          server-id: ossrh
          cache: maven
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Build and deploy
        run: |
          mvn -B install
          mkdir -p release
          cp $(find ./target -maxdepth 1 -type f -name "*.jar") ./release/
          mvn -B deploy
        env:
           MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
           MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
           MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - uses: actions/upload-artifact@v4
        with:
          name: conectus-java
          path: ./release/
      - name: Upload release asset
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ./release/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}